# Generated by Django 2.0.13 on 2019-12-03 01:09

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='analise',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
